---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
#  - name: centos-6.4

suites:
  - name: filefilter
    run_list:
      - recipe[filefilter_test::default]
    attributes:
